### ISSUE TITLE
[Proposal] Play Tetris Game

### ISSUE THREAD

**Issue by hargup** [felvin-search/instant-apps#110]
# Summary
Add an instant app for Tetris, so that you are never bored.

# Example search queries

- Tetris
- Play Tetris

# Implementation (optional)

You can choose to create your own tetris game, or choose one from available NPM packages.
You can look at the implementation of [snake game for references](https://github.com/felvin-search/instant-apps/pull/109).

# Context

**Comment by Nahdus** [comment]
I am (@sudde from discord) working on it. You may assign this to me.

**Comment by sahil-shubham** [comment]
Assigned the issue to you @Nahdus, looking forward to your PR.

**Comment by Nahdus** [comment]
pull request #129 has been merged
