### ISSUE TITLE
Search for Instant apps

### ISSUE THREAD

**Issue by xypnox** [felvin-search/instant-apps#123]
Currently the only way to see the available apps is in the `src/apps/` folder. A more user friendly interface with app names and description of what they do would help in app discovery and therefore usage.

**Comment by OrkoHunter** [comment]
Absolutely! Something like a marketplace is cooking https://docs.felvin.com/features/instant-apps/marketplace :)

**Comment by hargup** [comment]
This was done and you can see the results here https://docs.felvin.com/instant-apps/marketplace
