### ISSUE TITLE
[Chore] Publish the apps to NPM

### ISSUE THREAD

**Issue by OrkoHunter** [felvin-search/instant-apps#15]
All the apps in this repository should be published as a single package to NPM.

TODOs

- [ ] Setup a release workflow
- [ ] Setup NPM secret to do so

**Comment by OrkoHunter** [comment]
@felvin-search/maintainers please share your npm usernames so that I can add you to the felvin-search org on NPM

**Comment by rakaar** [comment]
@OrkoHunter 
Just created an npm account.
Username - `rakaar`
Profile - https://www.npmjs.com/~rakaar

**Comment by sahil-shubham** [comment]
@OrkoHunter 
My npm account/username - [sahil-shubham](https://www.npmjs.com/~sahil-shubham)

**Comment by hargup** [comment]
Username: - `hargup`
Profile: - https://www.npmjs.com/~hargup

**Comment by OrkoHunter** [comment]
Progress so far - Published package can not be imported from another package.

We are not sure if the entrypoint "publishConfig.main" inside package.json is really helping.

**Comment by OrkoHunter** [comment]
Update, `main` in package.json is indeed the entrypoint when importing a package.
