### ISSUE TITLE
[Proposal] Pokédex app ("pikachu stats")

### ISSUE THREAD

**Issue by hargup** [felvin-search/instant-apps#176]
# Summary
Create an app to show stats of pokemons.

<img width="382" alt="Screenshot 2021-10-15 at 10 27 57 AM" src="https://user-images.githubusercontent.com/2477788/137528911-592bc831-06ac-4c4e-b6ee-248224117416.png">

# Example search queries

- pikachu stats
- Bulbasaur info

# Implementation (optional)

- Poké API has a free API to fetch pokemon stats https://pokeapi.co/
- There is a defunk JS pokedex project, you might be able to take hints of css from there https://github.com/nolanlawson/pokedex.org

# Context

Are you telling me you don't find Pikachu's cute 🙄⚡️

**Comment by chirag828049** [comment]
Indeed they are very cute (i.e. I am working on it )

**Comment by sahil-shubham** [comment]
@chirag828049 Great! Looking forward to it.
