### ISSUE TITLE
[Bug] TV Show - Overfitting search queries to tv show name

### ISSUE THREAD

**Issue by shubh-agrawal** [felvin-search/instant-apps#202]
## Screenshot(s)

![image](https://user-images.githubusercontent.com/11351081/138888343-51da26ef-f4dd-4007-9c1b-19075f986553.png)

![image](https://user-images.githubusercontent.com/11351081/138888493-6cd9d56c-dd35-41c4-b585-7c58b817616e.png)

![image](https://user-images.githubusercontent.com/11351081/138888701-4d69c102-aa36-412f-84bf-0700ad382062.png)

## Affected search queries

- tetris
- trends
- tictac

## Summary

The tv show instant app is dominating the search query terms and over enthusiastically pushes the tv show cards

For example,
In the first affected query, user is expecting to get the game of tetris but receives some tv show card
In subsequent affected queries, tv show cards are pushed even for non-matching terms 

## Possible solution

Compare a threshold value with the match score delivered by the response json from tv show search api https://api.tvmaze.com/search/shows?q=${filteredQuery}. As seen in deployed implementation, there is no such check of confidence in the returned score.

Anything below 0.75 (or something derived empirically) should not be displayed to the user

## Your Environment

- Browser information: Chrome
- Operating system: Windows

**Comment by sahil-shubham** [comment]
Fixed with #222
