### ISSUE TITLE
`TS2322`: Type `'undefined'` is not assignable to type `'Promise<any>'`

### ISSUE THREAD

**Issue by FirePing32** [felvin-search/instant-apps#219]
After creating a fresh instant-app from `yarn create-app`, changing the `data` variable inside the `queryToData()` function to anything(string, object) breaks the app with the following error -
```bash
TS2322: Type '({ query }: { query: any; }) => { name: string; } | undefined' is 
not assignable to type 'queryToData'.
  Type '{ name: string; } | undefined' is not assignable to type 'Promise<any>'.
    Type 'undefined' is not assignable to type 'Promise<any>'.
```

The exact issue for this breakdown is not known. A temporary fix would be to make `queryToData()` `async`, even if the function does not perform any `GET`/`POST` requests.

**Comment by FirePing32** [comment]
@sahil-shubham Please add `bug` label.

**Comment by hargup** [comment]
I think this was fixed. @FirePing32 please feel free to reopen if the issue persists. Thanks for reporting the bug 😄
