### ISSUE TITLE
[Proposal] url encoder/decoder

### ISSUE THREAD

**Issue by sahil-shubham** [felvin-search/instant-apps#224]
# Summary

This app can be used to encode or decode URLs in the search bar itself.

# Example search queries

- url encode https://felvin.com
- url decode https%3A%2F%2Ffelvin.com

# Implementation (optional)

 There are built in functions for this in javascript namely `decodeURI()` and `encodeURI()`

**Comment by shobhit10058** [comment]
@sahil-shubham can I work on this issue? I have made it and its working in my machine.
![screenshot](https://user-images.githubusercontent.com/56156171/144757634-ff855bc6-cc07-440d-a81a-2e7db7c4bf86.png)

**Comment by sahil-shubham** [comment]
@shobhit10058 Awesome! make a pull request and we can discuss everything there.

**Comment by sahil-shubham** [comment]
Fixed with #252
