### ISSUE TITLE
[Proposal] stopwatch

### ISSUE THREAD

**Issue by sahil-shubham** [felvin-search/instant-apps#225]
# Summary

This is a stopwatch instant app.

# Example search queries

- stopwatch
# Implementation (Optional)
Maybe use: https://www.npmjs.com/package/react-stopwatch

**Comment by adarshares** [comment]
@sahil-shubham  mentor, I would like to work on this issue

**Comment by sahil-shubham** [comment]
Assigned, looking forward to your contribution.

**Comment by adarshares** [comment]
@sahil-shubham mentor , I have done this task, it looks like this 
![Screenshot from 2021-12-08 05-28-10](https://user-images.githubusercontent.com/94792019/145151673-fa99d81c-7570-44d9-b9a9-5a00c72f5c77.png)
s:
