### ISSUE TITLE
[Proposal] What day

### ISSUE THREAD

**Issue by sahil-shubham** [felvin-search/instant-apps#231]
# Summary

This instant app would tell about what day a particular date was, or would be.

# Example search queries

- What day was 9/12/2000
- What day 9/9/2049

# Implementation (Optional)

No external library / API needed, the JavaScript `Date getDay()` method should suffice. The input can be of type date

**Comment by sidkhuntia** [comment]
I would like to work on it.

**Comment by sidkhuntia** [comment]
# Summary



This shows the day on a particular date entered or a query.

# Example search queries



- <insert search query one> what day was yesterday
- <insert search query two> what day is it 
- <insert search query two> what day was on 15/04/2002


![Screenshot from 2021-12-06 20-50-19](https://user-images.githubusercontent.com/77291662/144872557-abf1e549-362a-428b-84cb-fe1ff28b7841.png)
![Screenshot from 2021-12-06 20-50-53](https://user-images.githubusercontent.com/77291662/144872565-7978ee63-6753-4781-aa0c-52498a17db2d.png)


# Implementation



I have used the ``` new Date().getDay() ``` method to convert the date and the passed the putput throughan aaray having the day names.

**Comment by sahil-shubham** [comment]
@sidkhuntia Already implemented? That's awesome! 

Make a PR and we can discuss things there.

**Comment by sidkhuntia** [comment]
Done !
