### ISSUE TITLE
[Proposal] Roman numbers

### ISSUE THREAD

**Issue by sahil-shubham** [felvin-search/instant-apps#235]
# Summary

This instant app converts a number in query or through a text to roman numbers

# Example search queries

- roman numbers for 420
- roman for 69

# Implementation (Optional)

Any external library or API should not be necessary. Check this out for a hint: https://stackoverflow.com/a/41358305
Optionally, a similar algorithm can be used to convert from roman to numeral too. A proper error message should display if the input Roman expression is not allowed

**Comment by AyushK-101** [comment]
I would like to work on this issue, please assign it to me @sahil-shubham

**Comment by sahil-shubham** [comment]
Assigned, thanks @AyushK-101

**Comment by sahil-shubham** [comment]
@AyushK-101 Any updates? if you are facing any issue or want feedback on any design change, you can make a [WIP] (work in progress) pull request and we can discuss things there.

**Comment by AyushK-101** [comment]
I am trying to set up the project locally, I will let you know if I need any help.

**Comment by sahil-shubham** [comment]
@AyushK-101 Are you still working on this issue?

**Comment by AyushK-101** [comment]
Pardon me, I got quite busy and I might not be able to make time to work on the issue

**Comment by UtkJaiswal** [comment]
Issue has been resolved https://github.com/felvin-search/instant-apps/pull/291.
