### ISSUE TITLE
[Proposal] Metronome

### ISSUE THREAD

**Issue by sahil-shubham** [felvin-search/instant-apps#237]
# Summary

This is a metronome app.

# Example search queries

- Metronome

# Implementation (Optional)

This looks promising: https://www.npmjs.com/package/@kevinorriss/react-metronome. Otherwise creating it from scratch too shouldn't be too hard, but care should be taken that time doesn't lag

**Comment by irenejoeunpark** [comment]
Hi @sahil-shubham, Please check PR #276 for the changes
