### ISSUE TITLE
[Question] Installing Packages

### ISSUE THREAD

**Issue by Reza9472** [felvin-search/instant-apps#262]
Hey whenever I try to install a new package, the package is installed then I get this
![Screen Shot 2021-12-07 at 10 37 56 PM](https://user-images.githubusercontent.com/69704498/145144109-b47c4e7a-9fd5-4381-a9a0-8e462d78b72b.png)

And after running `yarn install` , I get this

![Screen Shot 2021-12-07 at 10 40 20 PM](https://user-images.githubusercontent.com/69704498/145144323-9272ad6b-661f-4ae3-a9ec-dc42546a958a.png)

what am I missing?
It's the same with any libraries that I have tried

**Comment by sahil-shubham** [comment]
I am unable to see the directory in the screenshots. If you want to install a new package in a particular app, you would have inside that app's folder. On the other hand, you can install all the packages of the repository by running `yarn install` in the root itself.

**Comment by sahil-shubham** [comment]
@Reza9472 Did the above instruction solve your problem?

**Comment by Reza9472** [comment]
@sahil-shubham yes it did!
Apologies, forgot to close the issue

**Comment by sahil-shubham** [comment]
Happy that it's sorted, thanks for reaching out. Looking forward to your contribution.

**Comment by Reza9472** [comment]
@sahil-shubham Sure thing!
I'll definitely send my PR by tomorrow
