### ISSUE TITLE
[Enhacement] Hello world instant app - Change the language according to the search query

### ISSUE THREAD

**Issue by hargup** [felvin-search/instant-apps#263]
## Screenshot(s)

<img width="930" alt="Screenshot 2021-12-07 at 9 25 27 PM" src="https://user-images.githubusercontent.com/2477788/145153211-fe31d90f-05e3-417e-a890-37f82837c76d.png">

## Affected search queries

- hello world `language name`
## Summary

Right now "hello world" app always show the hello world program from javascript. We can parse the query and show the hello world for the language specified.

## Possible solution

- Look at the currency conversion app to see how the query parsing is done. 

## Your Environment

- Browser information (e.g Chrome v92):
- Operating system: (e.g. mac OS Big Sur)

**Comment by Aniket-508** [comment]
Can I take this up? @hargup

**Comment by sahil-shubham** [comment]
Feel free to work on this @Aniket-508 Assigning this to you.

**Comment by Aniket-508** [comment]
Hey, I guess its already done!
![15](https://user-images.githubusercontent.com/71957423/145236894-a3fe590a-c423-40b5-be5b-a2743ed60bc5.JPG)

**Comment by Aniket-508** [comment]
This is the query parsing part right? @sahil-shubham 

![16](https://user-images.githubusercontent.com/71957423/145254602-f0b67a38-46ea-453f-8ba9-62837adb910b.JPG)

**Comment by sahil-shubham** [comment]
@Aniket-508 We can have something like this, although currency convertor's query parsing is more complicated than needed. Maybe we can try splitting the query with "hello world" and seeing if the rest of the query contains a language or not.

**Comment by sahil-shubham** [comment]
@Aniket-508 Any updates? if you are facing any issue or want feedback on any design change, you can make a [WIP] (work in progress) pull request and we can discuss things there.

**Comment by Aniket-508** [comment]
@sahil-shubham I actually am facing problem in setting the project locally like the project has so many apps and I have individually setup the node modules for each of the package json file. Any help on that?

**Comment by sahil-shubham** [comment]
I wasn't able to understand your problem properly, can you explain what steps you went through while setting up the repository? 

You can also join our discord server and interact with other developers: https://discord.gg/WkxvFkzutA

**Comment by Aniket-508** [comment]
I forked the project, then cloned it and after opening it in code editor, I just ran the command "yarn" to install all the dependencies

**Comment by sahil-shubham** [comment]
@Aniket-508 Are you still working on this issue?

**Comment by Aniket-508** [comment]
Nope, you can unassign me.

**Comment by KevinDanae** [comment]
Hi, can i take this?

**Comment by hargup** [comment]
Of course @KevinDanae go ahead ✌️
