### ISSUE TITLE
[Proposal] Count number of words or characters

### ISSUE THREAD

**Issue by OrkoHunter** [felvin-search/instant-apps#28]
# Summary

It should be possible to paste a piece of text and get the word count and/or character count for it.

# Example search queries

- count words
- word count
- word counter
- character count
- count letters

# Implementation (optional)

Character count - String.length should do it. Probably should also show non-whitespace characters.
Word count - split by `' '` and return length. Or do some regex `\w` magic if you're feeling brave. 😂 

# Context

Very handy when writing something which has a word/character limit. Look at `wc` CLI for inspiration.

**Comment by hargup** [comment]
I wanted to use this yesterday when we were drafting tweets :P
