### ISSUE TITLE
[Proposal] Pronounce English words

### ISSUE THREAD

**Issue by Reckon77** [felvin-search/instant-apps#288]
# Summary

Gives the correct pronunciation of a given English word using text to speech.
# Example search queries

- pronounce intellectual
- pronounce entrepreneur

# Context

<img width="541" alt="pronounce" src="https://user-images.githubusercontent.com/56126160/148483302-a123ae8a-1e72-4c94-80e8-fd6f13125ad2.png">

**Comment by sahil-shubham** [comment]
Our dictionary app already provides a small audio clip with the pronunciation, maybe we can just make the dictionary app also render on the queries "pronounce `word`" or "`word` pronunciation".

**Comment by Reckon77** [comment]
Just checked the dictionary app. The solution suggested by you could definitely solve the issue.

**Comment by sahil-shubham** [comment]
Would you like to work on this?

**Comment by Reckon77** [comment]
@sahil-shubham ya sure
