### ISSUE TITLE
[Enhancement] url shortner -- use url specified in the query string

### ISSUE THREAD

**Issue by hargup** [felvin-search/instant-apps#292]
## Screenshot(s)

**Current behavior**
<img width="972" alt="Screenshot 2022-01-15 at 9 24 17 PM" src="https://user-images.githubusercontent.com/2477788/149648459-84836452-ddb5-4025-aa7d-039ced44224c.png">

**Expected behavior**
<img width="957" alt="Screenshot 2022-01-15 at 9 24 26 PM" src="https://user-images.githubusercontent.com/2477788/149648460-690f6248-4238-46fd-b0a1-61fd52a5c048.png">

## Affected search queries

- shorten url https://docs.felvin.com/instant-apps/architecture

## Summary

Currently the shorten url app doesn't automatically take the url from the query string. Fixing this behavior will allow me and other people to shorten urls from their address bar directly, instead of having to manually enter the url after the shorten url app appears.

FYI, I faced this problem.

## Possible solution

Parse the url from the query string and use it in the shorten url app

**Comment by KevinDanae** [comment]
Hi! 
This is my first contribution to an open source 😨 
If you think the change would be cool and if something can be improved, I will gladly do it
