### ISSUE TITLE
Fix publishing of instant apps packages

### ISSUE THREAD

**Issue by hargup** [felvin-search/instant-apps#311]
Publishing of Instant-apps packages is failing. For some reason, the registry url cheat-sh package has `/` encoded as `%2f` which is leading the package publishing github action to fail. Link to failing action:

- https://github.com/felvin-search/instant-apps/runs/5312143108?check_suite_focus=true

![](https://media.discordapp.net/attachments/923102197250678795/946229254985756722/Screenshot_2022-02-23_at_9.16.44_PM.png)

**Comment by sahil-shubham** [comment]
Don't think the `/` being encoded to `%2f` is the reason for failure. You can find our published packages with an without encode, example `https://registry.npmjs.org/@felvin-community%2faddress-pincodes`

**Comment by hargup** [comment]
This was fixed with #316
