### ISSUE TITLE
[Bug] Courier tracking app appears too often

### ISSUE THREAD

**Issue by hargup** [felvin-search/instant-apps#325]
## Screenshot(s)

<img width="939" alt="Screenshot 2022-02-27 at 5 58 14 PM" src="https://user-images.githubusercontent.com/2477788/155903553-45214156-a139-48e1-b15a-9a9b0a3be02d.png">

## Affected search queries

- track chrome store metrics
- track metrics

## Summary

The Courier tracking app is only checking for "track" keyword, it should be more strict matching.

## Your Environment

- Browser information (e.g Chrome v92):
- Operating system: (e.g. mac OS Big Sur)

**Comment by palashb01** [comment]
hey !! @hargup i think i can work on this issue,  Please assign this issue to me also could you please tell upto what keyboards the courier tracking app should appear.

**Comment by hargup** [comment]
@palashb01 go ahead :) Looking forward to your contributions.

**Comment by palashb01** [comment]
@hargup I have resolved the issue could you please mark this issue as hacktoberfest 2022 accepted, I will PR for this issue tomorrow.
