### ISSUE TITLE
[Proposal] json to yaml convertor

### ISSUE THREAD

**Issue by hargup** [felvin-search/instant-apps#330]
# Summary

Create a json to yaml convertor

# Example search queries

- json to yaml

# Implementation (optional)

You can create `json to yaml` by following the implementation of [json to csv](https://github.com/felvin-search/instant-apps/tree/7538bef499fafac0ef55e94b4fa4f7032a5f1732/apps/json-to-csv) and 
[yaml to json](https://github.com/felvin-search/instant-apps/tree/master/apps/yaml-to-json) and [json to csv] apps.

# Context

**Comment by Sync271** [comment]
Can I work on this?

**Comment by hargup** [comment]
Ofc, please go ahead 😄
