### ISSUE TITLE
[Proposal] Search Icon should be clickable

### ISSUE THREAD

**Issue by Sync271** [felvin-search/instant-apps#334]
# Summary

On most search engines, the search icon is clickable and it also feels intuitive to click on it.

<img width="674" alt="Screenshot 2022-03-08 at 5 52 25 PM" src="https://user-images.githubusercontent.com/2477788/157339498-9f16196f-5aab-436d-a454-e74da5fc75d8.png">

# Example search queries

None

# Implementation (optional)

Just wrap the current Icon component with a span and add submit option to it.
Following line should be the relevant place to make the modification.
https://github.com/felvin-search/instant-apps/blob/master/packages/sandbox/src/components/SearchBox.tsx#L104

# Context

This issue is there only on the sandbox.felvin.com, things work fine on felvin.com

**Comment by hargup** [comment]
@Sync271 thanks for reporting this @Sync271, I have added a screenshot and few more additional details to help a contributor pick up this issue.
