### ISSUE TITLE
[Bug] YAML to JSON - crashes on entering invalid YAML

### ISSUE THREAD

**Issue by Sync271** [felvin-search/instant-apps#337]
## Screenshot(s)

https://www.loom.com/share/fee7c4fe11ca4a3d94eca05c99ac1bb7

## Affected search queries

yaml to json

## Summary

On entering invalid JSON data into the text field it crashes and removed the app from the screen, you can get the app back without reloading the page. This might be a problem when users try to type their own YAML text 

## Possible solution

try and catch the error without crashing the app

## Your Environment

- Browser information (e.g Chrome v92): Microsoft Edge Version 99.0.1150.39 (Official build) (64-bit)
- Operating system: Windows 10 Pro

**Comment by hargup** [comment]
Thanks for reporting this, this is should be an straight forward fix, so marked as `good first issue`. Feel free to take it up.

**Comment by Sync271** [comment]
I'll take this
