### ISSUE TITLE
Felvin -- HackOFiesta Submission

### ISSUE THREAD

**Issue by hargup** [felvin-search/instant-apps#358]
Event details - https://www.notion.so/Felvin-b7b2691f91cd435c807948d59a134d76

**Submissions end on Sunday 24th April, 9 PM IST [Convert to your timezone](https://www.timeanddate.com/worldclock/converter.html?iso=20211017T163000&p1=tz_ist)**

Leave a comment in this issue to make your submission! You can edit your comments until the submission period. Use the following format -

```
- Short summary of the instant app(s) you created (1 or 2 lines)

<Summary>

- Link to Pull Request(s) *you* created *during* the hackathon

- <PR 1 link>
- <PR 2 link>

- Link to any demo videos, slides, screenshots, Tik Tok videos, etc. (Maximum 2 minutes, Minimum 10 seconds)

<Video link>

- Your email address where we should reach out for giving away the prize

<Email>

About you (People want to know about you! Tell us what you do, where do you study, what are you learning these days, etc.)

<Tell us about yourself>

```

**Comment by jim4067** [comment]
- Short summary of the instant app(s) you created (1 or 2 lines)
 This instant app corrupts a pdf doc.

- Link to Pull Request(s) *you* created *during* the hackathon
https://github.com/felvin-search/instant-apps/pull/360
- <PR 2 link>

- Link to any demo videos, slides, screenshots, Tik Tok videos, etc. (Maximum 2 minutes, Minimum 10 seconds)
Corrupt PDF link -> https://github.com/jim4067/instant-apps/blob/corrupt-pdf/apps/corrupt-pdf/src/files/screenshot.jpg


- Your email address where we should reach out for giving away the prize
jimmyimpulse2@gmail.com

About you (People want to know about you! Tell us what you do, where do you study, what are you learning these days, etc.)
Uni student. I am currently trying to learn about Solana and web 3.0.

**Comment by lonewolf2002** [comment]
- Short summary of the instant app(s) you created (1 or 2 lines)

I have created two instant apps so far. Both apps are pretty responsive so far.
Pomodoro Tracker:- As of now,3 modes like Pomodoro, short break, and long break are fixed, but they can be set manually. Audio trigger implemented.
Minesweeper: You can flag by right-clicking and playing as normal rules of the minesweeper

- Link to Pull Request(s) *you* created *during* the hackathon
- <PR 1 link>
- https://github.com/felvin-search/instant-apps/pull/361
- <PR 2 link>
- https://github.com/felvin-search/instant-apps/pull/362

- Link to any demo videos, slides, screenshots, Tik Tok videos, etc. (Maximum 2 minutes, Minimum 10 seconds)

Video Link PR2: https://drive.google.com/file/d/1eUdUgAlLPePRtRfcje3uYCBgLLPWXzoq/view?usp=sharing

- Your email address where we should reach out for giving away the prize

grp.gyanaranjan@gmail.com

About you (People want to know about you! Tell us what you do, where do you study, what are you learning these days, etc.)
I am currently a CSE sophomore at VSSUT,burla. I love to contribute to open source, and along with that I also competitive coding. Currently, I am learning backend and advanced cp concepts.

**Comment by hargup** [comment]
Everyone please note that we have extended the submission deadline by 12 more hours.

**Comment by Sync271** [comment]
### Summary
An app that helps you solve wordle faster while not spoiling the game for you. It is more of a copilot.

### PR Links
#### PR1
- https://github.com/felvin-search/instant-apps/pull/364
- https://www.loom.com/share/10711e5d46f7494f91f1e173f7832d24


### About Me
email: abhikm271@gmail.com

Self-taught programmer, who is relatively new to open source and trying to contribute every day. I currently work with a german startup that took me in and taught me a lot. Found a great learning opportunity there. Looking forward to being a bit more ambitious every day.

**Comment by chirag-ghosh** [comment]
- Short summary of the instant app(s) you created (1 or 2 lines)
Working in a team of 2. @rajivharlalka and I created 3 instant apps. One is ASCII art generator. Another instant app provides book info from isbn number. The third is a note-taking app which helps take notes in markdown and saves in localStorage.

- Link to Pull Request(s) *you* created *during* the hackathon

- #368 
- #369 

- Link to any demo videos, slides, screenshots, Tik Tok videos, etc. (Maximum 2 minutes, Minimum 10 seconds)
We have put screenshots in the respective PRs.

- Your email address where we should reach out for giving away the prize
rajivharlalka009@gmail.com cghosh828049@gmail.com

About you (People want to know about you! Tell us what you do, where do you study, what are you learning these days, etc.)
Partners in Crime, Rajiv and me love to collaborate and work together as you might have guessed. We are sophomores at IIT Kharagpur and we absolutely love javascript. While Rajiv generally dwells in backend, I love the frontend side of things.
