### ISSUE TITLE
[Chore] Setup an automated release process

### ISSUE THREAD

**Issue by OrkoHunter** [felvin-search/instant-apps#46]
Requirements

* Preferably one-click (either by doing a Release on GitHub, or by merging a PR by some release bot like https://github.com/atlassian/changesets)
* Ability to write changelog with releases. These get picked up by depandabots and such when bumping the version of the package on consumer projects. It's also nice to see releases described by some release notes. Ideally, every PR should contain a changelog.

Look into `yarn publish-apps` command which was added in https://github.com/felvin-search/instant-apps/pull/45

Let's start with daily releases and move to weekly releases as things get more stable.

**Comment by sahil-shubham** [comment]
This was fixed by #77, closing this.
