### ISSUE TITLE
Rendering the apps during development

### ISSUE THREAD

**Issue by j-tesla** [felvin-search/instant-apps#5]
I did not find a script to actually render the snippets apps when I tried a build a new one. Am I missing something?

**Comment by j-tesla** [comment]
> Hi @j-tesla, glad to see that you are trying to build a snippet app. We working a script to make it easy for everyone to test snippetapps while people are developing them.
> 
> Meanwhile would love to know what you are building and would love to help you in any way possible.
> 
> cc @OrkoHunter

Thank you. I thought I'd build an app for cryptocurrency rates.

**Comment by OrkoHunter** [comment]
@j-tesla That's so exciting to hear! We're currently working on solving this exact problem - let's leave this issue open until we tie all the loose ends and make the release. Stay tuned :)

**Comment by hargup** [comment]
Hello @j-tesla,
We did a bunch of things this weekend to make it easy for you to build and test snippet apps (now called instant apps). Please checkout our [contribution guide](https://github.com/felvin-search/instant-apps/blob/master/CONTRIBUTING.md), happy hacking :)

**Comment by OrkoHunter** [comment]
Closing the issue, since it's possible to do this. Thanks again for reporting!
