### ISSUE TITLE
[Proposal] Courier Package Tracking

### ISSUE THREAD

**Issue by sahil-shubham** [felvin-search/instant-apps#50]
# Summary

An instant app to track your package using the tracking id. 

# Example search queries

- FedEx tracking
- Delhivery tracking

# Implementation (optional)

Some of the courier providers have documentation for their APIs, like Delhivery  and FedEx. 

# Context

**Comment by hargup** [comment]
Comment from @DefCon-007

> For neera context, you can start with integrating such thing for Pickrr(http://www.pickrr.com/) can be good start.
It is an IIT Gwahati startup which aggregates delivery services and provide a common platform for tracking and scheduling deliveries across various providers. A lot of D2C brands currently use them.
Maybe neera can get a shoutout from them too after integration is live.
