### ISSUE TITLE
[Bug] Currency conversion - the result should be more visible

### ISSUE THREAD

**Issue by OrkoHunter** [felvin-search/instant-apps#54]
## Screenshot(s)

Us:
![Screen Shot 2021-08-27 at 09 37 58](https://user-images.githubusercontent.com/8065913/131090962-72140ae2-4fc8-4a2e-8a07-75f2f50a9519.png)

Google:
![Screen Shot 2021-08-27 at 09 38 49](https://user-images.githubusercontent.com/8065913/131090989-7903f05d-e77c-4ded-bb3d-74eb13747be1.png)

## Affected search queries

- 500 usd to inr

and similar

## Summary

When I'm doing a conversion, I want the resulting number to be most visible, so that I can leave the website quickly.

## Possible solution

Highlight the result on top and move the text box based conversion area to the bottom.

## Your Environment

- Browser information (e.g Chrome v92):
- Operating system: (e.g. mac OS Big Sur)

**Comment by jim4067** [comment]
Hello 👋🏾 

Here is a working implementation of what I was able to come up with.

![working-implementation](https://user-images.githubusercontent.com/30603522/131255160-2e754d6f-09e9-4815-b417-df6080561b7d.jpg)

I would like to get feedback on the PR.

**Comment by OrkoHunter** [comment]
@jim4067 That looks amazing! 😍

**Comment by jim4067** [comment]
> @jim4067 That looks amazing!

Thank you
