### ISSUE TITLE
[RFC] Suggest or upvote tagline for instant apps

### ISSUE THREAD

**Issue by OrkoHunter** [felvin-search/instant-apps#6]
What is a good one-liner to explain Instant apps on Neera search?

Add a comment in this issue or upvote existing ones!

**Comment by OrkoHunter** [comment]
Get every app you need, fast

**Comment by OrkoHunter** [comment]
There is an app for every search query

**Comment by OrkoHunter** [comment]
Apps that give you instant answer

**Comment by hargup** [comment]
Each ❤️ is equal to 3 👍

**Comment by hargup** [comment]
Search box is now an app store 🎉

**Comment by hargup** [comment]
Lets go with " Your search box is now an app store! 🎉 "

Closing the issue.
