### ISSUE TITLE
[Proposal] Latex Renderer

### ISSUE THREAD

**Issue by rakaar** [felvin-search/instant-apps#66]
# Summary

Render Latex Math Equations. 

# Example search queries
- Math Latex renderer
- Render Latex Math
- Latex math compile

# Context

Reference - https://www.codecogs.com/latex/eqneditor.php

**Comment by SuyashSonawane** [comment]
Hi @hargup, is this issue open to work? I would like to contribute

**Comment by hargup** [comment]
Hi @SuyashSonawane, Sure! Feel free to pick this up 😁
Let us know if we can support the effort in anyway.

cc @OrkoHunter
