### ISSUE TITLE
[Proposal] Color converter & Palette generator

### ISSUE THREAD

**Issue by xypnox** [felvin-search/instant-apps#69]
# Summary

Add a color converter and palette generator as a instant app.

This will facilitate:

- Conversion of colors from the formats (with opacity):
  - rgb
  - hsl
  - hex
- Palette generator for the selected color

# Example search queries

- #ffffff
- rgba(0, 120, 239, 0) to hex
- #ffffff palette
- random color
- random palette

# Implementation (optional)

The current currency converter fits well for this conversion. The https://www.thecolorapi.com/ is a decent API with support for palette generation and conversion.

# Context

This app becomes useful for the designers/frontend developers and people in general for figuring out and converting colors.

**Comment by xypnox** [comment]
NGL I like the issue number.

**Comment by OrkoHunter** [comment]
😂

**Comment by OrkoHunter** [comment]
It's no coincidence.
