### ISSUE TITLE
Use the utility API in the create-app template

### ISSUE THREAD

**Issue by OrkoHunter** [felvin-search/instant-apps#91]
## What

Use the trigger based matcher function introduced in https://github.com/felvin-search/instant-apps/pull/89 for the `dataToQuery` field of new apps created using `yarn create-app`.

Add a comment that they can replace it with their own custom function if they want to.

## Why

We want a new app to be as small and simple as possible, with the possibility of expanding on top of it.

**Comment by sahil-shubham** [comment]
Didn't know there was already an issue, but solved this with #124
